export enum NcStatus {
  NC_DESTINATION_UNKNOWN = "NC_DESTINATION_UNKNOWN",
  NC_DESTINATION_REACHABLE = "NC_DESTINATION_REACHABLE",
  NC_DESTINATION_NOT_REACHABLE = "NC_DESTINATION_NOT_REACHABLE",
  NC_NOT_CONFIGURED = "NC_NOT_CONFIGURED",
}
