export enum Status {
  // PENDING (group id: 1) - general status codes
  PENDING_WAITING_DELIVERY = "PENDING_WAITING_DELIVERY",
  PENDING_ENROUTE = "PENDING_ENROUTE",
  PENDING_ACCEPTED = "PENDING_ACCEPTED",
  // UNDELIVERABLE (group id: 2) - general status codes
  UNDELIVERABLE_REJECTED_OPERATOR = "UNDELIVERABLE_REJECTED_OPERATOR",
  UNDELIVERABLE_NOT_DELIVERED = "UNDELIVERABLE_NOT_DELIVERED",
  // DELIVERED (group id: 3) - general status codes
  DELIVERED_TO_OPERATOR = "DELIVERED_TO_OPERATOR",
  DELIVERED_TO_HANDSET = "DELIVERED_TO_HANDSET",
  // EXPIRED (group id: 4) - general status codes
  EXPIRED_EXPIRED = "EXPIRED_EXPIRED",
  EXPIRED_DLR_UNKNOWN = "EXPIRED_DLR_UNKNOWN",
  // REJECTED (group id: 5) - general status codes
  REJECTED_NETWORK = "REJECTED_NETWORK",
  REJECTED_PREFIX_MISSING = "REJECTED_PREFIX_MISSING",
  REJECTED_DND = "REJECTED_DND",
  REJECTED_SOURCE = "REJECTED_SOURCE",
  REJECTED_NOT_ENOUGH_CREDITS = "REJECTED_NOT_ENOUGH_CREDITS",
  REJECTED_SENDER = "REJECTED_SENDER",
  REJECTED_DESTINATION = "REJECTED_DESTINATION",
  REJECTED_PREPAID_PACKAGE_EXPIRED = "REJECTED_PREPAID_PACKAGE_EXPIRED",
  REJECTED_DESTINATION_NOT_REGISTERED = "REJECTED_DESTINATION_NOT_REGISTERED",
  REJECTED_ROUTE_NOT_AVAILABLE = "REJECTED_ROUTE_NOT_AVAILABLE",
  REJECTED_FLOODING_FILTER = "REJECTED_FLOODING_FILTER",
  REJECTED_SYSTEM_ERROR = "REJECTED_SYSTEM_ERROR",
  REJECTED_DUPLICATE_MESSAGE_ID = "REJECTED_DUPLICATE_MESSAGE_ID",
  REJECTED_INVALID_UDH = "REJECTED_INVALID_UDH",
  REJECTED_MESSAGE_TOO_LONG = "REJECTED_MESSAGE_TOO_LONG",
  MISSING_TO = "MISSING_TO",
  // REJECTED (group id: 5) - Voice status codes
  REJECTED_INVALID_AUDIO_FILE_URL = "REJECTED_INVALID_AUDIO_FILE_URL",
  REJECTED_UNSUPPORTED_LANGUAGE = "REJECTED_UNSUPPORTED_LANGUAGE",
  REJECTED_MESSAGE_IS_EMPTY = "REJECTED_MESSAGE_IS_EMPTY",
  REJECTED_INVALID_NOTIFY_URL = "REJECTED_INVALID_NOTIFY_URL",
  REJECTED_INVALID_NOTIFY_CONTENT_TYPE = "REJECTED_INVALID_NOTIFY_CONTENT_TYPE",
  REJECTED_INVALID_DTMF_SIGN = "REJECTED_INVALID_DTMF_SIGN",
  REJECTED_INVALID_DTMF_TIMEOUT = "REJECTED_INVALID_DTMF_TIMEOUT",
  REJECTED_INVALID_RING_TIMEOUT = "REJECTED_INVALID_RING_TIMEOUT",
  REJECTED_INVALID_CALL_TIMEOUT = "REJECTED_INVALID_CALL_TIMEOUT",
  REJECTED_INVALID_MACHINE_DETECTION = "REJECTED_INVALID_MACHINE_DETECTION",
  REJECTED_INVALID_ACTIONS = "REJECTED_INVALID_ACTIONS",
  REJECTED_INVALID_ACTION_GROUPS = "REJECTED_INVALID_ACTION_GROUPS",
  // UNDELIVERABLE (group id: 2) - push notifications status codes
  UNDELIVERABLE_NO_DESTINATION = "UNDELIVERABLE_NO_DESTINATION",
  // REJECTED (group id: 5) - push notifications status codes
  REJECTED_NO_APPLICATION = "REJECTED_NO_APPLICATION",
}
